name: bloc_lens
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: 3.5.0-47.0.dev

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/macros
      ref: main
  meta: ^1.14.0

dev_dependencies:
  leancode_lint: ^12.0.0

dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main
