name: bloc_lens
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-61.0.dev

dependencies:
  bloc: ^8.1.4
  lens_base:
    path: ../lens_base

dev_dependencies:
  leancode_lint: ^12.0.0
