name: bloc_lens_macros
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/leancodepl/bloc_lens
homepage: https://github.com/leancodepl/bloc_lens/tree/main/packages/bloc_lens_macros

environment:
  sdk: ^3.5.0-61.0.dev

dependencies:
  bloc: ^8.1.4
  bloc_lens:
    path: ../bloc_lens
  collection: ^1.18.0
  macros: ^0.1.0-main.3
  meta: ^1.14.0

dev_dependencies:
  leancode_lint: ^12.0.0

dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main
  _macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_macros
      ref: main
